name: Claude Auto Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  claude-auto-review:
    # Skip draft PRs
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            # PR Review for #${{ github.event.pull_request.number }}
            
            ## CRITICAL: USE ONLY INLINE COMMENTS - NO SUMMARY COMMENTS
            
            First, read the team review guidelines from `.claude/commands/team-review.md` to understand the review standards and process.

            Then follow these steps:

            ## 1. Load Review Guidelines
            Read the file `.claude/commands/team-review.md` for complete review instructions, including:
            - Reviewer persona and philosophy
            - Review priorities and what gets rejected
            - Comment format and examples
            - Technology-specific checks

            ## 2. Check Existing Comments
            Before reviewing, check what comments/suggestions already exist:
            ```bash
            gh pr view ${{ github.event.pull_request.number }} --comments
            ```
            
            ## 3. Get PR Diff and Analyze Full Files
            ```bash
            gh pr diff ${{ github.event.pull_request.number }}
            ```
            **IMPORTANT**: For each file in the diff:
            - Read the ENTIRE file to understand full context
            - Analyze how changes affect the whole file
            - Look for patterns, duplications, and inconsistencies

            ## 4. Apply Review Process
            Follow the comprehensive review process defined in team-review.md, focusing on:
            - MANDATORY FIXES (breaking changes, security holes, performance killers,React violations, TypeScript issues, accessibility)
            - CODE QUALITY issues (naming, patterns, dead code)

            ## 5. Create ONLY Inline Review Comments (NO SUMMARY):
            
            **GITHUB SUGGESTION BLOCK FORMAT**:
            When creating inline comments, the body MUST contain this EXACT format:
            - Line 1: Your human-like comment explaining the issue
            - Line 2: Three backticks followed immediately by the word "suggestion" (no spaces)
            - Line 3: The exact replacement code for that specific line
            - Line 4: Three backticks to close the suggestion block
            
            This creates a GitHub UI button that says "Commit suggestion" that users can click.
            
            **FORBIDDEN COMMANDS - DO NOT USE:**
            - ❌ NEVER use: `gh pr comment` (creates summary comments)
            - ❌ NEVER use: `gh pr review --comment` (creates summary)
            - ❌ NEVER post a general review summary
            
            **REQUIRED: Use ONLY inline comments at specific lines:**
            
            ### Step 1: Discover the correct API endpoints dynamically
            ```bash
            # Method A: Get from PR metadata
            PR_DATA=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }})
            
            # Extract the reviews URL from the PR data
            REVIEWS_URL=$(echo "$PR_DATA" | jq -r '._links.reviews.href' | sed 's|https://api.github.com||')
            
            # Extract the comments URL from the PR data  
            COMMENTS_URL=$(echo "$PR_DATA" | jq -r '._links.comments.href' | sed 's|https://api.github.com||')
            
            # Method B: If _links not available, construct from pattern
            if [ -z "$REVIEWS_URL" ]; then
              REVIEWS_URL="repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews"
              COMMENTS_URL="repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments"
            fi
            ```

            ### Step 2: Start a pending review
            ```bash
            # Use the discovered reviews endpoint
            REVIEW_ID=$(gh api "$REVIEWS_URL" \
              --method POST \
              --field commit_id="${{ github.event.pull_request.head.sha }}" \
              --field event="PENDING" \
              --jq '.id')
            ```

            ### Step 3: Add inline comments at specific lines
            For EACH issue found in the code, create a separate inline comment.
            
            **THE BODY MUST USE REAL NEWLINES - USE HEREDOC SYNTAX**:
            
            **CRITICAL INSTRUCTION FOR SUGGESTIONS**:
            When you find code that needs fixing (like `any` types, console.logs, eval(), etc):
            1. Create a human-like comment explaining the issue
            2. Include a suggestion block with the EXACT replacement code
            3. The suggestion must use proper markdown formatting
            
            **Example commands you should run for each issue:**
            
            For a type issue on line 4 of UserProfile.tsx:
            ```bash
            # Create the comment body with proper formatting
            BODY=$(cat <<'EOF'
This needs proper typing, not `any`:
```suggestion
const UserProfile = ({ userId }: { userId: string }) => {
```
EOF
            )
            
            # Post the comment
            gh api "$COMMENTS_URL" \
              --method POST \
              --field commit_id="${{ github.event.pull_request.head.sha }}" \
              --field path="src/components/UserProfile.tsx" \
              --field line=4 \
              --field side="RIGHT" \
              --field body="$BODY"
            ```
            
            For removing console.log on line 6:
            ```bash  
            BODY=$(cat <<'EOF'
Remove the console.log before merging:
```suggestion
  // Removed console.log for production
```
EOF
            )
            ```
            
            For fixing eval() security issue:
            ```bash
            BODY=$(cat <<'EOF'
Never use eval() - it's a massive security hole. Parse this safely instead:
```suggestion
    return JSON.parse(expr);
```
EOF
            )
            
            gh api "$COMMENTS_URL" \
              --method POST \
              --field commit_id="${{ github.event.pull_request.head.sha }}" \
              --field path="src/components/UserProfile.tsx" \
              --field line=6 \
              --field side="RIGHT" \
              --field body="$BODY"
            ```
            
            **CRITICAL for GitHub suggestions to work:**
            - The body field MUST contain actual newlines (not \n)
            - Use heredoc syntax: BODY=$(cat <<'EOF' ... EOF)
            - The suggestion block MUST be exactly: three backticks + suggestion
            - After the suggestion code, close with three backticks
            - This creates a "Commit suggestion" button in GitHub's UI
            
            **IMPORTANT**: The suggestion block in the body should look EXACTLY like this:
            ```
            Your comment here explaining the issue.
            ```suggestion
            const correctCode = 'replacement line';
            ```
            ```

            ### Step 4: Submit the review (comments only, no summary)
            ```bash
            # Submit the pending review with COMMENT event (not APPROVE/REQUEST_CHANGES)
            gh api "$REVIEWS_URL/${REVIEW_ID}/events" \
              --method POST \
              --field event="COMMENT"
            ```

            **REMEMBER:**
            - Create one inline comment per issue
            - Use line numbers from the diff
            - Include suggestion blocks for fixes
            - DO NOT create any summary comment
            - The line number must be from the DIFF (+/- lines), not the file line number
            - Use "side":"RIGHT" for additions, "side":"LEFT" for deletions
            - If API structure changes, the dynamic discovery will adapt

            Follow the tone and standards defined in team-review.md - be direct, provide concrete fixes, no gentle language.

          claude_args: '--allowed-tools "Bash(gh api:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(npm install),Bash(npm run lint),Bash(npm test),Bash(npm run build)"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
