name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            You were mentioned in a comment. Please respond to the user's request.
            
            If this is on a pull request and code review is requested:
            1. First, read the team review guidelines from `.claude/commands/team-review.md`
            2. Check existing comments: gh pr view ${{ github.event.issue.number || github.event.pull_request.number }} --comments
            3. Get the PR diff using: gh pr diff ${{ github.event.issue.number || github.event.pull_request.number }}
            4. Apply the review standards and process defined in team-review.md
            5. Provide feedback using GitHub CLI commands (SKIP if similar comment exists):
               - For general comments: `gh pr comment <PR_NUMBER> --body "Your comment"`
               - For reviews: `gh pr review <PR_NUMBER> --comment --body "Review"`
               - Use GitHub's suggestion format for code fixes:
                 ```suggestion
                 // Your suggested code
                 ```
            
            Note: GitHub automatically renders suggestion blocks that users can commit directly.
            
            Otherwise, respond to the user's request as appropriate.
          claude_args: '--allowed-tools "Bash(git:*),Bash(gh:*),Bash(npm install),Bash(npm run lint),Bash(npm test),Bash(npm run build)"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

