name: Claude Auto Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  claude-auto-review:
    # Skip draft PRs
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            Review PR #${{ github.event.pull_request.number }} and provide comprehensive feedback.

            Steps:
            1. Use `gh pr diff ${{ github.event.pull_request.number }}` to get the PR diff
            
            2. Analyze the code changes for:
               - Code quality and best practices
               - Security vulnerabilities  
               - Performance problems
               - Missing tests
               - React hooks usage issues
               - TypeScript type safety
               - Accessibility concerns
            
            3. Create a PR review with inline comments:
               a. Start a review: 
                  REVIEW_ID=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
                    --method POST \
                    --field commit_id="${{ github.event.pull_request.head.sha }}" \
                    --field event="PENDING" \
                    --jq '.id')
               
               b. For each issue found, add inline comments using:
                  gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/comments \
                    --method POST \
                    --field commit_id="${{ github.event.pull_request.head.sha }}" \
                    --field path="<file_path>" \
                    --field line=<line_number> \
                    --field side="RIGHT" \
                    --field body="<your_comment>"
               
               c. Submit the review:
                  gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews/${REVIEW_ID}/events \
                    --method POST \
                    --field event="COMMENT"
            
            Important: Use line numbers from the diff (+/- lines), not file line numbers
          
          claude_args: '--allowed-tools "Bash(gh api:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(npm install),Bash(npm run lint),Bash(npm test),Bash(npm run build)" --timeout 900000'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
